// A "catalog" is everything the shared collection flow needs to know about one
// kind of thing we catalog (records or books): which API to look it up on,
// which components render it, and the copy used for labels/toasts/empty states.
//
// Records and books share the same item shape — title stored as "Artist -
// Author - Title", plus year/label/genre/coverImage/barcode — so one flow in
// CollectionView.jsx drives both.

import * as discogs from './api/discogs'
import * as books from './api/books'
import { t } from './i18n'
import { splitArtistTitle } from './utils/match'
import { decadeOf } from './utils/browse'
import AlbumCard from './components/AlbumCard'
import AlbumGrid from './components/AlbumGrid'
import AlbumDetail from './components/AlbumDetail'
import ManualAddModal from './components/ManualAddModal'
import BookCard from './components/BookCard'
import BookGrid from './components/BookGrid'
import BookDetail from './components/BookDetail'
import BookManualAddModal from './components/BookManualAddModal'

// Feature flag for the gamification suite (Phase 1 § Play — rollout-plan.md §1):
// OFF by default, so nothing ships until validated. Flip to true to preview
// release 1.1 (Collection Persona + share card) behind the "Play" entry point.
export const GAMIFICATION_ENABLED = false

export const recordsCatalog = {
  kind: 'records',
  entity: 'record',
  collectionLabel: 'crate', // used in t() interpolation
  searchPlaceholder: 'Search your crate…',
  storage: 'records',
  api: discogs,
  getDetail: discogs.getReleaseDetail,
  lookupName: 'Discogs',
  formats: ['LP', 'EP', 'CD', '7"', '12"'],
  genreLabel: 'Genre',
  artistLabel: 'artist',
  artistPlaceholder: 'All artists',
  sortOptions: [
    { value: 'added', label: 'Recently added' },
    { value: 'artist', label: 'Artist A–Z' },
    { value: 'year', label: 'Year' },
    { value: 'format', label: 'Format' },
  ],
  // The Aisles (§ Phase 2): browse axes for the aisle picker. Each axis knows
  // how to extract its bin value(s) from an item; bins are counted client-side.
  browseAxes: [
    { id: 'genre', label: 'Genre', value: (item) => (item.genre || []).map((g) => String(g).trim()).filter(Boolean) },
    { id: 'artist', label: 'Artist', value: (item) => [splitArtistTitle(item.title).artist].filter(Boolean) },
    { id: 'decade', label: 'Decade', value: (item) => [decadeOf(item.year)] },
    { id: 'format', label: 'Format', value: (item) => (item.formatType ? [item.formatType] : []) },
    { id: 'label', label: 'Label', value: (item) => (item.label ? [item.label] : []) },
  ],
  components: {
    Card: AlbumCard,
    Grid: AlbumGrid,
    Detail: AlbumDetail,
    ManualAdd: ManualAddModal,
  },
  detailLink: (item) => `https://www.discogs.com/release/${item.discogsId}`,
  detailLinkLabel: 'View on Discogs ↗',
  copy: {
    emptyIcon: 'empty-disc',
    // Kind-specific overrides for the shared collection flow.
    // Components use t() as the primary source; these are fallbacks / overrides.
    emptyTitle: 'Your crate is empty',
    emptySub: 'Scan the barcode on a sleeve to catalog your first record.',
    emptyTagline: 'your crate, cataloged',
    emptyBtn: 'Scan a record',
    loading: 'Loading your crate…',
    addToast: 'Added to your crate',
    removeLabel: 'Remove from crate',
    lookingUp: 'Looking it up on Discogs…',
    noMatch: 'No matches found on Discogs.',
    resultGood: { label: 'Not in your crate yet', sub: "You don't have this one." },
    resultOwned: { label: 'Already in your crate', sub: 'This exact record is already yours.' },
    resultSame: { label: 'You already own this album', sub: 'Different pressing or format — check before buying.' },
    sameHeading: 'Other pressings you own',
    moreBy: (name, n) => `More by ${name} in your crate (${n})`,
    nothingElseBy: (name) => `Nothing else by ${name} in your crate`,
    moreRelated: (n) => `and ${n} more`,
    scanNext: 'Scan next',
    add: 'Add to crate',
    manualTitleRequired: 'Add a title — give this record a name first.',
    fabMenu: { label: 'Add options', scan: 'Scan barcode', searchTitle: 'Search by title', manual: 'Enter manually', scanCover: 'Scan cover' },
    // Cover OCR (§ cover-scan-ocr): photograph a sleeve with no readable
    // barcode and read the artist/title off it on-device.
    coverScan: {
      title: 'Scan a cover',
      help: 'Frame the front of the cover so the artist and title are readable.',
      capture: 'Capture',
      choosePhoto: 'Choose a photo',
      retake: 'Retake',
      identifying: 'Reading the cover…',
      noText: "Couldn't read the cover — try a clearer photo or enter the details manually.",
      searching: 'Looking it up…',
      timedOut: 'Reading the cover took too long — try again or pick a different photo.',
      error: 'Something went wrong with the camera or photo.',
      close: 'Cancel cover scan',
    },
    filterSheet: {
      artist: 'Artist',
      noArtists: 'No matching artists',
      clearArtist: 'Clear artist filter',
    },
    // The Floor (§ Phase 1): sectioned home — New arrivals / On loan / Pinned
    // shelves, then "Browse all". `dive` opens a random item.
    floor: {
      newArrivals: { title: 'New arrivals', kicker: 'Fresh in' },
      onLoan: { title: 'On loan', kicker: 'Out in the world' },
      pinned: { title: 'Pinned', kicker: 'Your picks' },
      browseAll: { title: 'Browse all', kicker: 'Everything' },
      dive: 'Crate dive',
      diveAria: 'Open a random record from your crate',
      pin: 'Pin to top',
      unpin: 'Unpin',
      pinnedToast: 'Pinned to your picks',
      unpinnedToast: 'Removed from your picks',
    },
    // Wishlist (§ Fix): a list of UNOWNED wants (e.g. scanned in a shop).
    // Not part of the owned crate until the user converts it.
    wishlist: {
      button: 'Wishlist',
      title: 'Your wishlist',
      empty: 'Your wishlist is empty — scan something in a shop and add it here.',
      addToCrate: 'Add to crate',
      addToCrateToast: 'Added to your crate',
      remove: 'Remove from wishlist',
      removeToast: 'Removed from your wishlist',
      ownIt: 'Own it',
      addedToast: 'Added to your wishlist',
      addToWishlist: 'Add to wishlist',
      resultWishlisted: { label: 'In your wishlist', sub: 'Add it to your crate when you own it.' },
    },
    browse: {
      label: 'Browse',
      title: 'Browse your crate',
      clear: 'Clear browse',
      empty: 'Nothing to show here yet.',
    },
    search: {
      results: (n, q) => `${n} ${n === 1 ? 'match' : 'matches'} for “${q}”`,
      clear: 'Clear search results',
      recentTitle: 'Recent searches',
      clearRecent: 'Clear recent',
      didYouMeanPrefix: 'Did you mean',
      done: 'Done',
    },
    stats: {
      button: 'Stats',
      title: 'Your crate, by the numbers',
      total: (n) => `${n} ${n === 1 ? 'item' : 'items'}`,
      byGenre: 'By genre',
      byDecade: 'By decade',
      empty: 'Nothing to count yet — add some items first.',
    },
    // Gamification (Phase 1 § Play): release 1.1 Collection Persona + share
    // card. Copy bridges t() (EN master in the i18n locales; other locales
    // inherit via fallback until the native-speaker pass lands — copy-bank §11).
    gamif: {
      nav: t('gamif.nav'),
      hint: t('gamif.hint', { collectionLabel: 'crate' }),
      persona: {
        title: t('gamif.persona.title'),
        headline: t('gamif.persona.headline', { collectionLabel: 'crate' }),
        emptyTitle: t('gamif.persona.emptyTitle', { entity: 'record' }),
        emptySub: t('gamif.persona.emptySub', { entity: 'record' }),
        loading: t('gamif.persona.loading', { collectionLabel: 'crate' }),
        share: t('gamif.persona.share'),
        shared: t('gamif.persona.shared'),
        hashtag: t('gamif.persona.hashtag'),
        tagline: t('gamif.persona.tagline'),
        stats: {
          count: t('gamif.persona.stat.count'),
          genres: t('gamif.persona.stat.genres'),
          artists: t('gamif.persona.stat.artists'),
          topDecade: t('gamif.persona.stat.topDecade'),
          topDecadePct: t('gamif.persona.stat.topDecadePct'),
          decades: t('gamif.persona.stat.decades'),
          labels: t('gamif.persona.stat.labels'),
          countries: t('gamif.persona.stat.countries'),
          artistAlbums: t('gamif.persona.stat.artistAlbums'),
          pressingsOfOne: t('gamif.persona.stat.pressingsOfOne'),
          albumsTwice: t('gamif.persona.stat.albumsTwice'),
          notesCount: t('gamif.persona.stat.notesCount'),
          oneDayBurst: t('gamif.persona.stat.oneDayBurst'),
          busiestMonth: t('gamif.persona.stat.busiestMonth'),
          jazzPct: t('gamif.persona.stat.jazzPct'),
        },
        archetypes: {
          'crate-digger': { name: t('gamif.persona.crateDigger'), verdict: t('gamif.persona.verdict.crateDigger') },
          'time-traveler': { name: t('gamif.persona.timeTraveler'), verdict: t('gamif.persona.verdict.timeTraveler') },
          'genre-tourist': { name: t('gamif.persona.genreTourist'), verdict: t('gamif.persona.verdict.genreTourist') },
          completist: { name: t('gamif.persona.completist'), verdict: t('gamif.persona.verdict.completist') },
          'impulse-buyer': { name: t('gamif.persona.impulseBuyer'), verdict: t('gamif.persona.verdict.impulseBuyer') },
          'one-timer': { name: t('gamif.persona.oneTimer'), verdict: t('gamif.persona.verdict.oneTimer') },
          'variant-collector': { name: t('gamif.persona.variantCollector'), verdict: t('gamif.persona.verdict.variantCollector') },
          'sophisticate': { name: t('gamif.persona.sophisticate'), verdict: t('gamif.persona.verdict.sophisticate') },
          fallback: { name: t('gamif.persona.fallback'), verdict: t('gamif.persona.verdict.fallback') },
        },
      },
      // Play surface tabs (release 1.2 / 1.4)
      tabs: {
        persona: t('gamif.tab.persona'),
        progression: t('gamif.tab.progression'),
        stories: t('gamif.tab.stories'),
      },
      // Release 1.2 — XP / levels / badges panel copy (issue #45)
      progression: {
        title: t('gamif.progression.title'),
        level: t('gamif.progression.level'),
        xp: t('gamif.progression.xp'),
        toNext: t('gamif.progression.toNext'),
        maxLevel: t('gamif.progression.maxLevel'),
        badgesTitle: t('gamif.progression.badgesTitle'),
        badgeLocked: t('gamif.progression.badgeLocked'),
        badgeComingSoon: t('gamif.progression.badgeComingSoon'),
        unlockToast: t('gamif.progression.unlockToast'),
        levelToast: t('gamif.progression.levelToast'),
        emptyTitle: t('gamif.progression.emptyTitle', { entity: 'record' }),
        emptySub: t('gamif.progression.emptySub', { entity: 'record' }),
        share: t('gamif.progression.share'),
        shared: t('gamif.progression.shared'),
        shareHeadline: t('gamif.progression.shareHeadline'),
        shareTagline: t('gamif.progression.shareTagline'),
        statXp: (n) => t('gamif.progression.statXp', { n: String(n) }),
        statItems: (n) => `${Number(n || 0)} ${Number(n) === 1 ? 'record' : 'records'}`,
        xpLabel: t('gamif.progression.xpLabel'),
        toastClose: t('gamif.progression.toastClose'),
        levels: [
          { title: t('gamif.level.records.1'), toast: t('gamif.levelToast.recordsTail') },
          { title: t('gamif.level.records.2'), toast: t('gamif.levelToast.recordsTail') },
          { title: t('gamif.level.records.3'), toast: t('gamif.levelToast.recordsTail') },
          { title: t('gamif.level.records.4'), toast: t('gamif.levelToast.recordsTail') },
          { title: t('gamif.level.records.5'), toast: t('gamif.levelToast.recordsTail') },
        ],
      },
      // Release 1.2 — badge names + unlock lines (copy-bank.md §5)
      badges: {
        digger: { name: t('gamif.badge.digger.name'), line: t('gamif.badge.digger.line') },
        pageturner: { name: t('gamif.badge.pageturner.name'), line: t('gamif.badge.pageturner.line') },
        'genre-tourist': { name: t('gamif.badge.genre-tourist.name'), line: t('gamif.badge.genre-tourist.line') },
        'time-traveler': { name: t('gamif.badge.time-traveler.name'), line: t('gamif.badge.time-traveler.line') },
        completist: { name: t('gamif.badge.completist.name'), line: t('gamif.badge.completist.line') },
        'impulse-buyer': { name: t('gamif.badge.impulse-buyer.name'), line: t('gamif.badge.impulse-buyer.line') },
        'sleeve-sleuth': { name: t('gamif.badge.sleeve-sleuth.name'), line: t('gamif.badge.sleeve-sleuth.line') },
        'balanced-diet': { name: t('gamif.badge.balanced-diet.name'), line: t('gamif.badge.balanced-diet.line') },
        'one-timer': { name: t('gamif.badge.one-timer.name'), line: t('gamif.badge.one-timer.line') },
        'variant-hoarder': { name: t('gamif.badge.variant-hoarder.name'), line: t('gamif.badge.variant-hoarder.line') },
        'friend-of-crate': { name: t('gamif.badge.friend-of-crate.name'), line: t('gamif.badge.friend-of-crate.line') },
        'quiz-whiz': { name: t('gamif.badge.quiz-whiz.name'), line: t('gamif.badge.quiz-whiz.line') },
      },
      // Release 1.4 — Shelf Stories panel copy (issue #44)
      stories: {
        headline: t('gamif.stories.headline', { collectionLabel: 'crate' }),
        emptyTitle: t('gamif.stories.emptyTitle'),
        emptySub: t('gamif.stories.emptySub', { entity: 'record' }),
        quest: t('gamif.stories.quest'),
        questSoon: t('gamif.stories.questSoon'),
        prev: t('gamif.stories.prev'),
        next: t('gamif.stories.next'),
        counter: t('gamif.stories.counter'),
        cards: {
          'year-span': { title: t('gamif.story.year-span.title'), body: t('gamif.story.year-span.body') },
          'decade-bias': { title: t('gamif.story.decade-bias.title'), body: t('gamif.story.decade-bias.body') },
          'era-lesson': { title: t('gamif.story.era-lesson.title'), body: t('gamif.story.era-lesson.body') },
          'country-mix': { title: t('gamif.story.country-mix.title'), body: t('gamif.story.country-mix.body') },
          series: { title: t('gamif.story.series.title'), body: t('gamif.story.series.body') },
          'one-timer': { title: t('gamif.story.one-timer.title'), body: t('gamif.story.one-timer.body') },
          'notes-coverage': { title: t('gamif.story.notes-coverage.title'), body: t('gamif.story.notes-coverage.body') },
          'total-pages': { title: t('gamif.story.total-pages.title'), body: t('gamif.story.total-pages.body') },
        },
      },
    },
    views: {
      title: 'Saved views',
      savePlaceholder: 'Name this view…',
      save: 'Save view',
      rename: 'Rename',
      delete: 'Delete view',
      empty: 'No saved views yet.',
      summary: (n) => `${n} ${n === 1 ? 'filter' : 'filters'}`,
    },
    lending: {
      section: t('lending.section'),
      statusOut: (name, date) => t('lending.statusOut', { name, date }),
      due: (date) => t('lending.due', { date }),
      overdue: t('lending.overdue'),
      overdueSince: (date) => t('lending.overdueSince', { date }),
      notOnLoan: t('lending.notOnLoan'),
      lend: t('lending.lend'),
      lendTitle: (entity) => t('lending.lendTitle', { entity }),
      borrower: t('lending.borrower'),
      borrowerPlaceholder: t('lending.borrowerPlaceholder'),
      contact: t('lending.contact'),
      dueDate: t('lending.dueDate'),
      confirmLend: t('lending.confirmLend'),
      nameRequired: t('lending.nameRequired'),
      return: t('lending.return'),
      returnConfirm: t('lending.returnConfirm'),
      lentToast: (name) => t('lending.lentToast', { name }),
      returnedToast: t('lending.returnedToast'),
      badge: t('lending.badge'),
      badgeOverdue: t('lending.badgeOverdue'),
      filter: t('lending.filter'),
      filterHint: t('lending.filterHint'),
      history: t('lending.history'),
      historyLent: (date) => t('lending.historyLent', { date }),
      historyReturned: (date) => t('lending.historyReturned', { date }),
    },
    view: {
      showing: (n, m) => `Showing ${Number(n || 0).toLocaleString()} of ${Number(m || 0).toLocaleString()}`,
      backToTop: 'Back to top',
    },
  },
}

export const booksCatalog = {
  kind: 'books',
  entity: 'book',
  collectionLabel: 'shelf', // used in t() interpolation
  searchPlaceholder: 'Search your shelf…',
  storage: 'books',
  api: books,
  getDetail: books.getBookDetail,
  lookupName: 'Google Books',
  formats: [], // books are looked up by ISBN — no format chips
  genreLabel: 'Category',
  artistLabel: 'author',
  artistPlaceholder: 'All authors',
  sortOptions: [
    { value: 'added', label: 'Recently added' },
    { value: 'artist', label: 'Author A–Z' },
    { value: 'title', label: 'Title A–Z' },
    { value: 'year', label: 'Year' },
  ],
  // The Aisles (§ Phase 2): browse axes for the aisle picker. Books have no
  // series field in the item shape, so the axes cover the data we actually have.
  browseAxes: [
    { id: 'category', label: 'Category', value: (item) => (item.genre || []).map((g) => String(g).trim()).filter(Boolean) },
    { id: 'author', label: 'Author', value: (item) => [splitArtistTitle(item.title).artist].filter(Boolean) },
    { id: 'year', label: 'Year', value: (item) => (item.year ? [String(item.year)] : []) },
  ],
  components: {
    Card: BookCard,
    Grid: BookGrid,
    Detail: BookDetail,
    ManualAdd: BookManualAddModal,
  },
  detailLink: (item) => item.infoLink || `https://books.google.com/books?id=${item.googleBooksId}`,
  detailLinkLabel: 'View on Google Books ↗',
  copy: {
    emptyIcon: 'empty-book',
    // Kind-specific overrides for the shared collection flow.
    emptyTitle: 'Your shelf is empty',
    lending: {
      section: t('lending.section'),
      statusOut: (name, date) => t('lending.statusOut', { name, date }),
      due: (date) => t('lending.due', { date }),
      overdue: t('lending.overdue'),
      overdueSince: (date) => t('lending.overdueSince', { date }),
      notOnLoan: t('lending.notOnLoan'),
      lend: t('lending.lend'),
      lendTitle: (entity) => t('lending.lendTitle', { entity }),
      borrower: t('lending.borrower'),
      borrowerPlaceholder: t('lending.borrowerPlaceholder'),
      contact: t('lending.contact'),
      dueDate: t('lending.dueDate'),
      confirmLend: t('lending.confirmLend'),
      nameRequired: t('lending.nameRequired'),
      return: t('lending.return'),
      returnConfirm: t('lending.returnConfirm'),
      lentToast: (name) => t('lending.lentToast', { name }),
      returnedToast: t('lending.returnedToast'),
      badge: t('lending.badge'),
      badgeOverdue: t('lending.badgeOverdue'),
      filter: t('lending.filter'),
      filterHint: t('lending.filterHint'),
      history: t('lending.history'),
      historyLent: (date) => t('lending.historyLent', { date }),
      historyReturned: (date) => t('lending.historyReturned', { date }),
    },
    emptySub: 'Scan the ISBN on a book to catalog your first title.',
    emptyTagline: 'your shelf, cataloged',
    emptyBtn: 'Scan a book',
    loading: 'Loading your shelf…',
    addToast: 'Added to your shelf',
    removeLabel: 'Remove from shelf',
    lookingUp: 'Looking it up on Google Books…',
    noMatch: 'No matches found on Google Books.',
    resultGood: { label: 'Not on your shelf yet', sub: "You don't have this one." },
    resultOwned: { label: 'Already on your shelf', sub: 'This exact book is already yours.' },
    resultSame: { label: 'You already own this book', sub: 'Different edition — check before buying.' },
    sameHeading: 'Other editions you own',
    moreBy: (name, n) => `More by ${name} on your shelf (${n})`,
    nothingElseBy: (name) => `Nothing else by ${name} on your shelf`,
    moreRelated: (n) => `and ${n} more`,
    scanNext: 'Scan next',
    add: 'Add to shelf',
    manualTitleRequired: 'Add a title — give this book a name first.',
    fabMenu: { label: 'Add options', scan: 'Scan barcode', searchTitle: 'Search by title', manual: 'Enter manually', scanCover: 'Scan cover' },
    // Cover OCR (§ cover-scan-ocr): photograph a jacket with no readable ISBN
    // and read the title/author off it on-device.
    coverScan: {
      title: 'Scan a cover',
      help: 'Frame the front of the cover so the title and author are readable.',
      capture: 'Capture',
      choosePhoto: 'Choose a photo',
      retake: 'Retake',
      identifying: 'Reading the cover…',
      noText: "Couldn't read the cover — try a clearer photo or enter the details manually.",
      searching: 'Looking it up…',
      timedOut: 'Reading the cover took too long — try again or pick a different photo.',
      error: 'Something went wrong with the camera or photo.',
      close: 'Cancel cover scan',
    },
    filterSheet: {
      artist: 'Author',
      noArtists: 'No matching authors',
      clearArtist: 'Clear author filter',
    },
    // The Floor (§ Phase 1): sectioned home — New arrivals / On loan / Pinned
    // shelves, then "Browse all". `dive` opens a random item.
    floor: {
      newArrivals: { title: 'New arrivals', kicker: 'Fresh in' },
      onLoan: { title: 'On loan', kicker: 'Out in the world' },
      pinned: { title: 'Pinned', kicker: 'Your picks' },
      browseAll: { title: 'Browse all', kicker: 'Everything' },
      dive: 'Shelf dive',
      diveAria: 'Open a random book from your shelf',
      pin: 'Pin to top',
      unpin: 'Unpin',
      pinnedToast: 'Pinned to your picks',
      unpinnedToast: 'Removed from your picks',
    },
    // Wishlist (§ Fix): a list of UNOWNED wants (e.g. scanned in a shop).
    // Not part of the owned shelf until the user converts it.
    wishlist: {
      button: 'Wishlist',
      title: 'Your wishlist',
      empty: 'Your wishlist is empty — scan something in a shop and add it here.',
      addToCrate: 'Add to shelf',
      addToCrateToast: 'Added to your shelf',
      remove: 'Remove from wishlist',
      removeToast: 'Removed from your wishlist',
      ownIt: 'Own it',
      addedToast: 'Added to your wishlist',
      addToWishlist: 'Add to wishlist',
      resultWishlisted: { label: 'On your wishlist', sub: 'Add it to your shelf when you own it.' },
    },
    browse: {
      label: 'Browse',
      title: 'Browse your shelf',
      clear: 'Clear browse',
      empty: 'Nothing to show here yet.',
    },
    // Gamification (Phase 1 § Play): release 1.1 Collection Persona + share
    // card. Copy bridges t() (EN master in the i18n locales; other locales
    // inherit via fallback until the native-speaker pass lands — copy-bank §11).
    gamif: {
      nav: t('gamif.nav'),
      hint: t('gamif.hint', { collectionLabel: 'shelf' }),
      persona: {
        title: t('gamif.persona.title'),
        headline: t('gamif.persona.headline', { collectionLabel: 'shelf' }),
        emptyTitle: t('gamif.persona.emptyTitle', { entity: 'book' }),
        emptySub: t('gamif.persona.emptySub', { entity: 'book' }),
        loading: t('gamif.persona.loading', { collectionLabel: 'shelf' }),
        share: t('gamif.persona.share'),
        shared: t('gamif.persona.shared'),
        hashtag: t('gamif.persona.hashtag'),
        tagline: t('gamif.persona.tagline'),
        stats: {
          count: t('gamif.persona.stat.countBooks'),
          genres: t('gamif.persona.stat.genresBooks'),
          artists: t('gamif.persona.stat.artistsBooks'),
          pages: t('gamif.persona.stat.pages'),
          longestBook: t('gamif.persona.stat.longestBook'),
          publishers: t('gamif.persona.stat.publishers'),
          unfinishedSeries: t('gamif.persona.stat.unfinishedSeries'),
          topAuthorPct: t('gamif.persona.stat.topAuthorPct'),
        },
        archetypes: {
          'couch-intellectual': { name: t('gamif.persona.couchIntellectual'), verdict: t('gamif.persona.verdict.couchIntellectual') },
          'series-starter': { name: t('gamif.persona.seriesStarter'), verdict: t('gamif.persona.verdict.seriesStarter') },
          'genre-hedonist': { name: t('gamif.persona.genreHedonist'), verdict: t('gamif.persona.verdict.genreHedonist') },
          'page-counter': { name: t('gamif.persona.pageCounter'), verdict: t('gamif.persona.verdict.pageCounter') },
          'one-series-wonder': { name: t('gamif.persona.oneSeriesWonder'), verdict: t('gamif.persona.verdict.oneSeriesWonder') },
          'first-edition-idealist': { name: t('gamif.persona.firstEditionIdealist'), verdict: t('gamif.persona.verdict.firstEditionIdealist') },
          fallback: { name: t('gamif.persona.fallback'), verdict: t('gamif.persona.verdict.fallback') },
        },
      },
      // Play surface tabs (release 1.2 / 1.4)
      tabs: {
        persona: t('gamif.tab.persona'),
        progression: t('gamif.tab.progression'),
        stories: t('gamif.tab.stories'),
      },
      // Release 1.2 — XP / levels / badges panel copy (issue #45)
      progression: {
        title: t('gamif.progression.title'),
        level: t('gamif.progression.level'),
        xp: t('gamif.progression.xp'),
        toNext: t('gamif.progression.toNext'),
        maxLevel: t('gamif.progression.maxLevel'),
        badgesTitle: t('gamif.progression.badgesTitle'),
        badgeLocked: t('gamif.progression.badgeLocked'),
        badgeComingSoon: t('gamif.progression.badgeComingSoon'),
        unlockToast: t('gamif.progression.unlockToast'),
        levelToast: t('gamif.progression.levelToast'),
        emptyTitle: t('gamif.progression.emptyTitle', { entity: 'book' }),
        emptySub: t('gamif.progression.emptySub', { entity: 'book' }),
        share: t('gamif.progression.share'),
        shared: t('gamif.progression.shared'),
        shareHeadline: t('gamif.progression.shareHeadline'),
        shareTagline: t('gamif.progression.shareTagline'),
        statXp: (n) => t('gamif.progression.statXp', { n: String(n) }),
        statItems: (n) => `${Number(n || 0)} ${Number(n) === 1 ? 'book' : 'books'}`,
        xpLabel: t('gamif.progression.xpLabel'),
        toastClose: t('gamif.progression.toastClose'),
        levels: [
          { title: t('gamif.level.books.1'), toast: t('gamif.levelToast.booksTail') },
          { title: t('gamif.level.books.2'), toast: t('gamif.levelToast.booksTail') },
          { title: t('gamif.level.books.3'), toast: t('gamif.levelToast.booksTail') },
          { title: t('gamif.level.books.4'), toast: t('gamif.levelToast.booksTail') },
          { title: t('gamif.level.books.5'), toast: t('gamif.levelToast.booksTail') },
        ],
      },
      // Release 1.2 — badge names + unlock lines (copy-bank.md §5)
      badges: {
        digger: { name: t('gamif.badge.digger.name'), line: t('gamif.badge.digger.line') },
        pageturner: { name: t('gamif.badge.pageturner.name'), line: t('gamif.badge.pageturner.line') },
        'genre-tourist': { name: t('gamif.badge.genre-tourist.name'), line: t('gamif.badge.genre-tourist.line') },
        'time-traveler': { name: t('gamif.badge.time-traveler.name'), line: t('gamif.badge.time-traveler.line') },
        completist: { name: t('gamif.badge.completist.name'), line: t('gamif.badge.completist.line') },
        'impulse-buyer': { name: t('gamif.badge.impulse-buyer.name'), line: t('gamif.badge.impulse-buyer.line') },
        'sleeve-sleuth': { name: t('gamif.badge.sleeve-sleuth.name'), line: t('gamif.badge.sleeve-sleuth.line') },
        'balanced-diet': { name: t('gamif.badge.balanced-diet.name'), line: t('gamif.badge.balanced-diet.line') },
        'one-timer': { name: t('gamif.badge.one-timer.name'), line: t('gamif.badge.one-timer.line') },
        'variant-hoarder': { name: t('gamif.badge.variant-hoarder.name'), line: t('gamif.badge.variant-hoarder.line') },
        'friend-of-crate': { name: t('gamif.badge.friend-of-crate.name'), line: t('gamif.badge.friend-of-crate.line') },
        'quiz-whiz': { name: t('gamif.badge.quiz-whiz.name'), line: t('gamif.badge.quiz-whiz.line') },
      },
      // Release 1.4 — Shelf Stories panel copy (issue #44)
      stories: {
        headline: t('gamif.stories.headline', { collectionLabel: 'shelf' }),
        emptyTitle: t('gamif.stories.emptyTitle'),
        emptySub: t('gamif.stories.emptySub', { entity: 'book' }),
        quest: t('gamif.stories.quest'),
        questSoon: t('gamif.stories.questSoon'),
        prev: t('gamif.stories.prev'),
        next: t('gamif.stories.next'),
        counter: t('gamif.stories.counter'),
        cards: {
          'year-span': { title: t('gamif.story.year-span.title'), body: t('gamif.story.year-span.body') },
          'decade-bias': { title: t('gamif.story.decade-bias.title'), body: t('gamif.story.decade-bias.body') },
          'era-lesson': { title: t('gamif.story.era-lesson.title'), body: t('gamif.story.era-lesson.body') },
          'country-mix': { title: t('gamif.story.country-mix.title'), body: t('gamif.story.country-mix.body') },
          series: { title: t('gamif.story.series.title'), body: t('gamif.story.series.body') },
          'one-timer': { title: t('gamif.story.one-timer.title'), body: t('gamif.story.one-timer.body') },
          'notes-coverage': { title: t('gamif.story.notes-coverage.title'), body: t('gamif.story.notes-coverage.body') },
          'total-pages': { title: t('gamif.story.total-pages.title'), body: t('gamif.story.total-pages.body') },
        },
      },
    },
    search: {
      results: (n, q) => `${n} ${n === 1 ? 'match' : 'matches'} for “${q}”`,
      clear: 'Clear search results',
      recentTitle: 'Recent searches',
      clearRecent: 'Clear recent',
      didYouMeanPrefix: 'Did you mean',
      done: 'Done',
    },
    view: {
      showing: (n, m) => `Showing ${Number(n || 0).toLocaleString()} of ${Number(m || 0).toLocaleString()}`,
      backToTop: 'Back to top',
    },
  },
}
