// Access-code normalization — the SINGLE normalization used everywhere a code
// is compared or indexed (findUserByCode, the `code:<normalized>` auth index,
// and the auth rate limiter). Stored codes are uppercase (generated by
// generateAccessCode), so every caller normalizes to trim + uppercase and all
// lookups agree regardless of how the code was typed.
export function normalizeCode(code) {
  return String(code ?? '').trim().toUpperCase()
}
